config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: [:update, :show] do
    get '/set_or_create_chatroom', to: 'chatrooms#set_or_create_chatroom'
  end

  post '/follow', to: 'users#follow'
  post '/unfollow', to: 'users#unfollow'

  resources :concerts, only: [:index, :show] do
    resources :attendances, only: [:create]
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    member do
      get :like
      get :unlike
    end
    resources :comments, only: [:create]

  end

  resources :attendances, only: :destroy

  resources :chatrooms, only: [:index, :show]  do
    resources :messages, only: :create
  end
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  has_many :messages
  has_many :users, through: :messages

  scope :get_chatroom, -> (user_a, user_b) {
    where(participant1_id: user_a.id, participant2_id: user_b.id)
    .or(where(participant1_id: user_b.id, participant2_id: user_a.id))
  }

  scope :get_chatrooms, -> (user) {
    where(participant1_id: user.id).or(where(participant2_id: user.id))
  }
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end

  def index
    @chatrooms = Chatroom.get_chatrooms(current_user)
    @messages = []
    @chatrooms.each do |chatroom|
      if chatroom.messages.empty?
        chatroom.destroy
      else
        last_message = chatroom.messages.last
        @messages << last_message
      end
    end
    if @chatrooms.empty?
      render :index
    end
    @messages = @messages.sort_by(&:created_at).reverse

  end

  def set_or_create_chatroom
    @user = User.find(params[:user_id])
    @search = Chatroom.get_chatroom(current_user, @user)
    if @search.empty?
      @chatroom = Chatroom.create(participant1_id: current_user.id, participant2_id: @user.id)
    else
      @chatroom = @search.first
    end
    @message = Message.new
    render :show
  end
end

app/views/chatrooms/index.html.erb
<div>
  <h5>Your messages</h5>
</div>

<% if @chatrooms.empty? %>
  <p class="text-center">You don't have any messages</p>
<% else %>
    <% @messages.each do |message| %>
      <div>
        <%= link_to chatroom_path(message.chatroom, user_id: message.find_other_user(current_user).id) do %>
          <div class="chat-index-card shadowed-box d-flex align-items-start message-gap" >
            <div>
              <small>
                <div class="chat-index-card-user">
                  <%= cl_image_tag message.find_other_user(current_user).avatar.key, class:"avatar"  %>
                </div>
              </small>
            </div>
            <div id="message-<%= message.id %>" class="message-width">
              <p class="message-username"><strong><%= message.find_other_user(current_user).username %></strong></p>
              <% if message.user.id != message.find_other_user(current_user).id %>
                <p>You: <%= message.content %></p>
              <% else %>
                <p ><%= message.content %></p>
              <% end %>
              <p class="message-time"><i><%= message.created_at.strftime("%a at %H:%M") %></i></p>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
<% end %>

app/views/chatrooms/show.html.erb
<div class="container chatroom"
    data-controller="chatroom-subscription"
    data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"
    data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">
  <%# <h1><%= @chatroom.id</h1>  %>

  <div class="messages" data-chatroom-subscription-target="messages">
    <% @chatroom.messages.each do |message| %>
      <div class="message-row d-flex <%= message.sender?(current_user) ?
                  'justify-content-end' : 'justify-content-start' %>">
        <div class="message-card <%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
          <%= render "messages/message", message: message %>
        </div>
      </div>
    <% end %>
  </div>


  <div>
    <%= simple_form_for [@chatroom, @message],
        html: { data: { action: "turbo:submit-end->chatroom-subscription#resetForm" },
        class: ""} do |f|%>
      <div class="chat-form d-flex align-items-start">
        <div class="chat-input flex-grow-1">
          <%= f.input :content, label: false, input_html: { class: "chat-input-style" } %>
        </div>
        <div>
          <%= f.submit "Send", class: "btn" %>
        </div>
      </div>
    <% end %>
  </div>
</div>