config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: [:update, :show] do
    get '/set_or_create_chatroom', to: 'chatrooms#set_or_create_chatroom'
  end

  post '/follow', to: 'users#follow'
  post '/unfollow', to: 'users#unfollow'

  resources :concerts, only: [:index, :show] do
    resources :attendances, only: [:create]
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    member do
      get :like
      get :unlike
    end
    resources :comments, only: [:create]

  end

  resources :attendances, only: :destroy

  resources :chatrooms, only: [:index, :show]  do
    resources :messages, only: :create
  end
end

app/models/user.rb
require "open-uri"

class User < ApplicationRecord
  after_create :set_default_avatar

  acts_as_favoritor

  has_one_attached :avatar
  has_one_attached :banner

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :attendances
  has_many :reviews, through: :attendances
  has_many :concerts, through: :attendances

  acts_as_followable
  acts_as_follower

  def attended?(concert)
    !find_attendance(concert).nil?
  end

  def attendance_info(concert)
    find_attendance(concert)
  end


  def set_default_avatar
    default_avatar_url = "https://hips.hearstapps.com/hmg-prod/images/sigourney-weaver-avatar-ii-the-way-of-water-1670323174.jpg?crop=0.500xw:0.949xh;0.299xw,0.0514xh&resize=1200:*"
    default_banner_url = "https://townsquare.media/site/62/files/2021/11/attachment-brian-ruiz.jpg?w=980&q=75"

    unless self.avatar.key.present?
      avatar = URI.open(default_avatar_url)
      self.avatar.attach(io: avatar, filename: "avatar.png", content_type: "image/png")
    end

    unless self.banner.key.present?
      banner = URI.open(default_banner_url)
      self.banner.attach(io: banner, filename: "banner.png", content_type: "image/png")
    end
  end

  private

  def find_attendance(concert)
    Attendance.find_by(concert: concert, user: self)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @reviews = @user.reviews.includes(:concert).order("concerts.date desc")
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  def follow
    @user = User.find(params[:id])
    current_user.follow(@user)
    redirect_to user_path(@user)
  end

  def unfollow
    @user = User.find(params[:id])
    current_user.stop_following(@user)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :age, :city, :bio, :avatar, :banner)
  end
end

app/views/users/_display_attendances.html.erb
<div class="offcanvas offcanvas-start" tabindex="-1" id="attendancesButton" aria-labelledby="offcanvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasLabel"> <%= user.username %>'s shows</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">

    <% @user.attendances.each do |attendance| %>
      <%= link_to concert_path(attendance.concert) do %>
        <%= render "user_card_attendance", attendance: attendance %>
     <% end %>
   <% end %>

  </div>
</div>

app/views/users/_display_followers.html.erb
<div class="offcanvas offcanvas-start" tabindex="-1" id="followerButton" aria-labelledby="offcanvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasLabel"> <%= user.username %>'s followers</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">

    <% @user.followers.each do |user| %>
      <%= link_to user_path(user) do %>
        <%= render "user_card_follow", user: user %>
     <% end %>
   <% end %>

  </div>
</div>

app/views/users/_display_following.html.erb
<div class="offcanvas offcanvas-start" tabindex="-1" id="followingButton" aria-labelledby="offcanvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasLabel"><%= user.username %> is following</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">

    <% @user.all_following.each do |user| %>
      <%= link_to user_path(user) do %>
        <%= render "user_card_follow", user: user %>
     <% end %>
   <% end %>

  </div>
</div>

app/views/users/_user_card_attendance.html.erb
<div class="attending-card shadowed-box" style="height: 85px">
  <%= cl_image_tag attendance.concert.artist.photo.key, class: "square-image", style: "width: 75px; object-fit: cover" %>
  <div class="attending-card-content">
    <p><%= attendance.concert.artist.name %> </p>
    <%= link_to "View concert", concert_path(attendance.concert) %>
  </div>
</div>

app/views/users/_user_card_follow.html.erb
<div class="attending-card shadowed-box">
  <%= cl_image_tag user.avatar.key, class:"avatar"  %>
  <div class="attending-card-content">
    <p><%= user.username %> </p>
    <%= link_to "View profile", user_path(user) %>
  </div>
</div>

app/views/users/_user_details_form.html.erb
<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottom">Edit Profile</button>

<div class="offcanvas offcanvas-bottom" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasBottomLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasBottomLabel">Edit Profile</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body small">
  <%= simple_form_for(user) do |f| %>
    <div class="container mt-5 mb-5 d-flex justify-content-center">
      <div class="card px-0 py-6">
        <div class="card-body">
          <h3 class="mt-4">Your profile information:</h3>
          <div class="row">
            <div class="col-sm-12">
              <%= f.input :username, placeholder: "Username", label: false %>
              <%= f.input :email, placeholder: "E-mail", label: false %>
              <%= f.input :age, placeholder: "Age", label: false %>
              <%= f.input :city, placeholder: "City", label: false %>
              <%= f.input :bio, placeholder: "Bio", label: false %>
              <%= f.input :avatar, as: :file, input_html: { multiple: false }, label: "Upload your avatar" %>
              <%= f.input :banner, as: :file, input_html: { multiple: false }, label: "Upload your background image" %>
            </div>
          </div>
        </div>
        <div class=" d-flex flex-column justify-content-center">
          <%= f.submit 'Update my profile', class:'btn btn-flat btn-big'%>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/users/_user_follow_button.html.erb
<div id="user-<%=user.id%>" style="">
  <% if current_user.following?(user) %>
    <%= button_to "Unfollow", {action: 'unfollow', id: user.id}, method: 'post',
      class: 'btn' %>
  <% elsif current_user != user %>
    <%= button_to "Follow", {action: 'follow', id: user.id}, method: 'post',
      class: 'btn' %>
  <% end %>
</div>

app/views/users/_user_followers.html.erb
<div class="btn" id="user-<%=user.id%>" style="">
  <% if current_user.following?(user) %>
    <%= button_to "Unfollow", {action: 'unfollow', id: user.id}, method: 'post',
      class: 'btn' %>
  <% elsif current_user != user %>
    <%= button_to "Follow", {action: 'follow', id: user.id}, method: 'post',
      class: 'btn' %>
  <% end %>
</div>

app/views/users/_user_message_button.html.erb
<div id="user-<%=user.id%>" style="">
  <%= link_to "Message", user_set_or_create_chatroom_path(user), class: "btn" %>
</div>

app/views/users/show.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.2)), url('<%= cl_image_path @user.banner.key %>')">
    <h2> <%= cl_image_tag @user.avatar.key, class:"avatar-large"  %> </h2>
    <h2><%= @user.username %></h2>
    <div class="container-banner">
      <p> <%= @user.city %> </p>
  <%  if @user == current_user %>
      <p> <%= render "users/user_details_form", user: @user %> </p>
  <% else %>
      <div class="d-flex justify-content-around">
        <div>
          <p> <%= render "users/user_follow_button", user: @user %> </p>
        </div>
        <div>
          <p> <%= render "users/user_message_button", user: @user, chatroom: @chatroom %> </p>
        </div>
  <% end %>
      </div>
    </div>
</div>
    </div>


<div class="d-flex card-stats-container justify-content-around text-center">

<button data-bs-toggle="offcanvas" data-bs-target="#attendancesButton" aria-controls="offcanvasBottomPast">
  <div class="card-stats p-2">
    <h3><strong><%= @user.attendances.count %></strong></h3>
    <h3>Shows</h3>
    </div>
    </button>
  <%= render "display_attendances", user: @user %>


  <button data-bs-toggle="offcanvas" data-bs-target="#followerButton" aria-controls="offcanvasBottomPast">
    <div class="card-stats p-2">
      <h3><strong> <%= @user.followers.count %> </strong></h3>
      <h3>Followers</h3>
    </div>
  </button>
  <%= render "display_followers", user: @user %>

  <button data-bs-toggle="offcanvas" data-bs-target="#followingButton" aria-controls="offcanvasBottomPast">
    <div class="card-stats p-2">
      <h3><strong> <%= @user.all_following.count %> </strong></h3>
      <h3>Following</h3>
    </div>
  </button>
  <%= render "display_following", user: @user %>
</div>

<div class="grid-container-single">
  <% @reviews.each do |review| %>
    <%= link_to "#{concert_path(review.concert)}" do %>
    <div class="user-review-card shadowed-box" style="height: 100px">
      <%= cl_image_tag review.concert.artist.photo.key, class:"square-image mh-100", style: "width: 100px; object-fit: cover" %>
      <div class="list-group user-review-card-content" >
        <p><strong><%= Artist.find(review.concert.artist_id).name %></strong></p>
        <p><%= "#{review.concert.city} - #{review.concert.date.strftime('%d/%m/%Y')}" %></p>
    <% end %>
    </div>

      <div class="list-group user-review-card-content text-center" style="width: 125px">
        <%= render "shared/rating", review: review %>
        <p><strong><%= link_to "Read Review", "#{concert_path(review.concert)}##{review.id}" %></strong></p>
      </div>
    </div>
   <% end %>
</div>