config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: [:update, :show] do
    get '/set_or_create_chatroom', to: 'chatrooms#set_or_create_chatroom'
  end

  post '/follow', to: 'users#follow'
  post '/unfollow', to: 'users#unfollow'

  resources :concerts, only: [:index, :show] do
    resources :attendances, only: [:create]
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    member do
      get :like
      get :unlike
    end
    resources :comments, only: [:create]

  end

  resources :attendances, only: :destroy

  resources :chatrooms, only: [:index, :show]  do
    resources :messages, only: :create
  end
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_likes.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 256 256" class="heart-fill">
<path d="M240 94c0 70-103.79 126.66-108.21 129a8 8 0 0 1-7.58 0C119.79 220.66 16 164 16 94a62.07 62.07 0 0 1 62-62c20.65 0 38.73 8.88 50 23.89C139.27 40.88 157.35 32 178 32a62.07 62.07 0 0 1 62 62Z"/>
</svg>

app/views/shared/_menu_bar_footer.html.erb
<div class="menu-bar container-fluid">
  <div class="flex-icon">
    <%= link_to root_path do %>
      <%= image_tag "Home.svg", alt: "Home" %>
    <% end %>
  </div>
  <div class="flex-icon">
    <%= link_to concerts_path do %>
      <%= image_tag "Vector.svg", alt: "search" %>
    <% end %>
  </div>
  <div class="flex-icon">
    <%= link_to chatrooms_path(@chatrooms) do %>
      <%= image_tag "chatbubbles.svg", alt: "search" %>
    <% end %>
  </div>
  <div class="flex-icon">
  <% if user_signed_in? %>
    <%= link_to user_path(current_user.id) do %>
      <%= image_tag "Profile.svg", alt: "profile" %>
    <% end %>
  <% else %>
    <%= link_to user_session_path do %>
      <%= image_tag "Profile.svg", alt: "profile" %>
    <% end %>
  <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container-fluid">
      <%= link_to root_path do %>
      <div class="navbar-logo">
        <%= image_tag "frontrow.svg" %>
        <p>frontrow</p>
      </div>
      <% end %>

    <div>
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= cl_image_tag current_user.avatar.key, class:"avatar"  %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
        <div>
        <%= link_to "Login", user_session_path, class: "btn" %>
        </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_not_liked.html.erb
<svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" viewBox="0 0 256 256", class="heart-fill">
<path d="M178 34c-21 0-39.26 9.47-50 25.34C117.26 43.47 99 34 78 34a60.07 60.07 0 0 0-60 60c0 29.2 18.2 59.59 54.1 90.31a334.68 334.68 0 0 0 53.06 37a6 6 0 0 0 5.68 0a334.68 334.68 0 0 0 53.06-37C219.8 153.59 238 123.2 238 94a60.07 60.07 0 0 0-60-60Zm-50 175.11C111.59 199.64 30 149.72 30 94a48.05 48.05 0 0 1 48-48c20.28 0 37.31 10.83 44.45 28.27a6 6 0 0 0 11.1 0C140.69 56.83 157.72 46 178 46a48.05 48.05 0 0 1 48 48c0 55.72-81.59 105.64-98 115.11Z"/>
</svg>

app/views/shared/_rating.html.erb
<div class="rating">
  <% review.rating.times do %>
    <div class="star">
      <%= image_tag "star.svg" %>
    </div>
  <% end %>
  <% (5-review.rating).times do %>
    <div class="star">
      <%= image_tag "emptystar.svg" %>
    </div>
  <% end %>
</div>