config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :users, only: [:update, :show] do
    get '/set_or_create_chatroom', to: 'chatrooms#set_or_create_chatroom'
  end

  post '/follow', to: 'users#follow'
  post '/unfollow', to: 'users#unfollow'

  resources :concerts, only: [:index, :show] do
    resources :attendances, only: [:create]
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [] do
    member do
      get :like
      get :unlike
    end
    resources :comments, only: [:create]

  end

  resources :attendances, only: :destroy

  resources :chatrooms, only: [:index, :show]  do
    resources :messages, only: :create
  end
end

app/models/concert.rb
class Concert < ApplicationRecord
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_city,
    against: [ :city, :venue ],
    using: {
      tsearch: { prefix: true }
    }
  pg_search_scope :search_by_artist,
    associated_against: {
      artist: [ :name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :artist
  has_many :attendances
  has_many :users, through: :attendances
  has_many :reviews, through: :attendances
  validates :venue, presence: true
  validates :city, presence: true
  validates :date, presence: true
end

app/controllers/concerts_controller.rb
require 'open-uri'
require 'nokogiri'

class ConcertsController < ApplicationController

  def index
    @city = params[:query_city]
    @artist = params[:query_artist]
    @concerts = Concert.all.order(date: :desc)
    @concerts = Concert.search_by_city(@city) if @city.present?
    @concerts = Concert.search_by_artist(@artist) if @artist.present?
    @concerts = Concert.search_by_artist(@artist).search_by_city(@city) if @artist.present? && @city.present?
  end

  def show
    @concert = Concert.find(params[:id])
    @reviews = @concert.reviews.order(created_at: :desc)
    @attendance = current_user.attendance_info(@concert)
    @review = Review.new
  end
end

app/views/concerts/_attending_card.html.erb
<% concert.attendances.each do |attendance| %>
  <%= link_to user_path(attendance.user) do %>
    <div class="attending-card shadowed-box">
      <%= cl_image_tag attendance.user.avatar.key, class:"avatar"  %>
      <div class="attending-card-content">
        <p><%= attendance.user.username %> is attending!</p>
        <%= link_to "View profile", user_path(attendance.user) %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/concerts/_comment.html.erb
<div class="d-flex mt-3">
  <%= link_to user_path(comment.user) do %>
    <div>
        <%= cl_image_tag comment.user.avatar.key, class:"avatar"  %>
    </div>
  <% end %>
  <div class="comment-right">
    <p><strong><%= comment.user.username %></strong></p>
    <p><%= comment.content %></p>
  </div>
</div>

app/views/concerts/_comment_form.html.erb
  <%= simple_form_for [review, comment], html: {class: "d-none", data: {review_comment_target:"form", action:"submit->review-comment#create"}} do |f| %>
    <div class="new_review_form">
      <div class="field">
        <%= f.input :content, as: :text, label: false, placeholder:"Type your comment", input_html: {id:"content_field"} %>
      </div>
      <div>
        <%= f.button :submit, ">" %>
      </div>
    </div>
  <% end %>

app/views/concerts/_concert_banner.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @concert.artist.photo.key %>')">
  <h2><%= concert.artist.name %></h2>
    <div class="container-banner">
      <p> <%= concert.venue %> -  <%= concert.city %> - <%= concert.date.strftime('%d/%m/%Y') %> </p>
      <p><%= image_tag "pplattended.svg", alt: "people check" %> <%= concert.attendances.count %> users attended</p>
        <% if Date.today <= concert.date %>
          <%= link_to "I'm attending", concert_attendances_path(concert), data: { turbo_method: :post }, class:"btn" %>
        <% elsif Date.today >= concert.date %>
          <% if current_user.attended?(concert) %>
            <%= link_to "Post a review", new_concert_review_path(concert, @review), class:"btn"%>
          <% else %>
            <%= link_to "I attended", concert_attendances_path(concert), data: { turbo_method: :post }, class:"btn" %>
          <% end %>
        <% end %>
  </div>
  <div class="attended">
    <% if current_user.attended?(concert) %>
        <%= link_to attendance_path(@attendance),
          data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove your attendance?" } do %>
            <div class="attended-icon">
              <p>I attended <%= image_tag "i attended.svg", alt: "person check" %></p>
            </div>
          <% end %>
    <% end %>
  </div>
</div>

app/views/concerts/_concert_card.erb
<div class="concert-card shadowed-box">
  <img src='https://kitt.lewagon.com/placeholder/users/arthur-littm' class="square-image" />
  <div class="concert-card-content">
    <p><strong><%= concert.artist.name %></strong></p>
    <p><%= concert.city %></p>
    <p><%= concert.date.strftime('%d/%m/%Y') %></p>
  </div>
</div>

app/views/concerts/_concert_card.html.erb
<div class="concert-card shadowed-box"
    data-toggle-upcoming-target="card"
     data-date="<%= concert.date %>">
  <%= cl_image_tag concert.artist.photo.key, class:"square-image"  %>
  <div class="concert-card-content">
    <p><strong><%= concert.artist.name %></strong></p>
    <p><%= concert.city %></p>
    <p><%= concert.date.strftime('%d/%m/%Y') %></p>
  </div>
</div>

app/views/concerts/_countdown.html.erb
<div class="countdown-container">
  <div class="countdown">
      <% date = (@concert.date.strftime('%d/%m/%Y').to_date - Date.today).to_i.to_s.chars %>
        <% date.each do |number| %>
          <div class="day">
            <p><%= number %></p>
          </div>
        <% end %>
  </div>
  <div>
    <h4>days left</h4>
  </div>
</div>

app/views/concerts/_display_attenders_past.html.erb
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasBottom" aria-labelledby="offcanvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasLabel">They attended the show</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <% @concert.attendances.each do |attendance| %>
      <%= render "users/user_card_follow", user: attendance.user %>
    <% end %>
  </div>
</div>

app/views/concerts/_review_card.html.erb
<div class="shadowed-box review-card" data-controller="review-comment" id=<%= review.id %>>
  <%= link_to user_path(review.user) do %>
   <div class="review-card-user">
      <%= cl_image_tag review.user.avatar.key, class:"avatar"  %>
      <p><strong><%= review.user.username %></strong></p>
   </div>
  <% end %>

  <% unless review.photos.count == 0 %>
    <div class="review-card-media">
      <%= cl_image_tag review.photos.first.key, class:"square-image" %>
    </div>
  <% end %>
  <div class="review-card-rating">
    <%= render "shared/rating", review: review %>
  </div>
  <div class="review-card-content">
    <p><%= review.content %></p>
  </div>

  <div class="review-card-interactions" data-controller="review-like" data-review-like-count-value=<%= review.favoritors.count %> data-review-like-liked-value=<%= current_user.favorited?(review) %>>
    <div class="interation-section">
      <div class="interaction-item">
        <%= image_tag "comment.svg", alt: "comment", data: {action: "click->review-comment#display"}%>
      </div>
      <div class="interaction-item">
        <p data-review-comment-target="count"><%= review.comments.count %></p>
      </div>
    </div>

    <div class="interation-section">
      <div class="interaction-item">
        <% if current_user.favorited?(review) %>
          <%= link_to unlike_review_path(review), data: { review_like_target: "icon", action:"click->review-like#like" }  do %>
              <%= render "shared/likes"%>
            <% end %>
        <% else %>
          <%= link_to like_review_path(review), data: { turbo_method: :post, review_like_target: "icon", action:"click->review-like#like" }  do %>
              <%= render "shared/not_liked"%>
          <% end %>
        <% end %>
      </div>
      <div class="interaction-item">
          <p data-review-like-target="likes" ><%= review.favoritors.count %></p>
     </div>
    </div>
  </div>

  <%= render "comment_form", {comment: @comment, review:review} %>

  <div data-review-comment-target="comments" class="d-none" >
    <% review.comments.order(created_at: :desc).first(3).each do |comment| %>
      <%= render "comment", comment: comment %>
    <% end %>
  </div>
</div>

app/views/concerts/_show_banner.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url('<%= cl_image_path @concert.artist.banner.key %>')">
  <h2><%= concert.artist.name %></h2>
    <div class="container-banner">
      <p> <%= concert.venue %> -  <%= concert.city %> - <%= concert.date.strftime('%d/%m/%Y') %> </p>
      <div>
        <button data-bs-toggle="offcanvas" data-bs-target="#offcanvasBottom" aria-controls="offcanvasBottomPast">
          <p><%= image_tag "pplattended.svg", alt: "people check" %> <%= pluralize(concert.attendances.count, "fan") %> attended</p>
        </button>
        <%= render "display_attenders_past" %>
      </div>
        <% if current_user.attended?(concert) %>
          <%= link_to "Post a review", new_concert_review_path(concert, @review), class:"btn"%>
        <% else %>
          <%= link_to "I attended", concert_attendances_path(concert), data: { turbo_method: :post }, class:"btn" %>
        <% end %>
    </div>

  <div class="attended">
    <% if current_user.attended?(concert) %>
      <%= link_to attendance_path(@attendance),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove your attendance?" } do %>
          <div class="attended-icon">
            <p>I attended <%= image_tag "i attended.svg", alt: "person check" %></p>
          </div>
      <% end %>
    <% end %>
  </div>

</div>

app/views/concerts/_upcoming_banner.html.erb
<div class="show-banner" style="background-image: linear-gradient(rgba(0,0,0,0.6),rgba(0,0,0,0.6)), url('<%= cl_image_path @concert.artist.banner.key %>')">
  <h2><%= concert.artist.name %></h2>
    <div class="container-banner">
      <p> <%= concert.venue %> -  <%= concert.city %> - <%= concert.date.strftime('%d/%m/%Y') %> </p>
          <p><%= image_tag "pplattended.svg", alt: "people check" %> <%= pluralize(concert.attendances.count, "fan") %> attending</p>
        <% if current_user.attended?(concert) %>
          <%= link_to "I'm attending", concert_attendances_path(concert), data: { turbo_method: :post }, class:"btn d-none" %>
        <% elsif  %>
          <%= link_to "I'm attending", concert_attendances_path(concert), data: { turbo_method: :post }, class:"btn" %>
        <% end %>
    </div>

  <div class="attending">
    <div>
      <%= link_to concert.tickets_url, target: :_blank do %>
        <p>Buy tickets <i class="fa-solid fa-ticket" style="color: #f9f5eb;"></i></p>
      <% end %>
    </div>
    <% if current_user.attended?(concert) %>
      <div class="attended-icon">
        <%= link_to attendance_path(@attendance),
        data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to remove your attendance?" } do %>
          <p>I'm attending <%= image_tag "i attended.svg", alt: "person check" %></p>
        <% end %>
      </div>
    <% end %>
  </div>

</div>

app/views/concerts/index.html.erb
<div data-controller="toggle-upcoming">
  <div>
    <h5>Find your show</h5>
  </div>

<div class="search-container">
  <%= form_with url: concerts_path, method: :get do %>
    <div class="search-form">
      <%= text_field_tag :query_artist,
            @artist,
            placeholder: "Type an artist",
            class: "search-input-style"
        %>
        <%= text_field_tag :query_city,
              @city,
              placeholder: "Type a city",
              class: "search-input-style"
        %>
      <%= submit_tag "Find", name: "", class: "btn" %>
    </div>
  <% end %>
</div>

  <div class="form-check form-switch search-container">
    <input class="form-check-input" type="checkbox" role="switch" id="flexSwitchCheckDefault" data-action="click->toggle-upcoming#hide">
    <label class="form-check-label" for="flexSwitchCheckDefault">Upcoming shows</label>
  </div>

  <div class="grid-container-single">
    <% if @concerts.empty? %>
      <div class="no-results">
        <p>Sorry, no concerts match your search. </p>
        <p>Please try again!</p>
      </div>
    <% else %>
      <% @concerts.each do |concert| %>
        <%= link_to concert_path(concert), data: { toggle_upcoming_target: "link" } do %>
          <%= render "concert_card", concert: concert %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/concerts/show.html.erb
<% if Date.today <= @concert.date %>
  <%= render "upcoming_banner", concert: @concert %>
  <%= render "countdown", concert: @concert %>
  <div class="grid-container-single">
    <%= render "attending_card", concert: @concert %>
  </div>
<% else %>
  <%= render "show_banner", concert: @concert %>
<% end %>

<div class="grid-reviews">
    <% @reviews.each do |review| %>
      <div>
        <%= render "review_card", review: review %>
      </div>
    <% end %>
</div>